"use client";
import Navbar from "@/components/Homepage/Navbar";
import Footer from "@/components/Homepage/Footer";
import { motion } from "framer-motion";
import { Twitter, Linkedin, Github, Brain, Shield, Rocket, Users } from "lucide-react";
import Link from "next/link";

const STATS = [
  { value: "450+", label: "Active Users" },
  { value: "1.5K+", label: "Roadmaps Generated", featured: true },
  { value: "2.3K+", label: "Mock Interviews" },
];

const VALUES = [
  { icon: Brain, label: "AI Precision", desc: "Every roadmap is generated by advanced AI that understands your current skill level, learning pace, and career goals — delivering truly personalized guidance.", color: "text-primary" },
  { icon: Shield, label: "Data Privacy", desc: "Your learning data stays yours. We use end-to-end encryption and never share your progress or personal information with third parties.", color: "text-accent" },
  { icon: Rocket, label: "Continuous Growth", desc: "We don't just point you toward a destination — we walk with you through every phase, milestone, and skill checkpoint on your learning journey.", color: "text-primary" },
  { icon: Users, label: "Inclusivity", desc: "Whether you're a student, a career switcher, or an experienced professional, CareerPilot adapts to where you are and where you want to go.", color: "text-accent" },
];

const TEAM = [
  { name: "Alvy Ahmed", role: "MERN Stack Developer", photo: "/alvy.jpg" },
  { name: "Ahnaf Abid", role: "MERN Stack Developer", photo: "/Ahnaf Abid.jpg" },
  { name: "Md. Asaduzzaman Masad", role: "Frontend Developer", photo: null },
  { name: "A.T.M Abdullah Al Mamun", role: "MERN Stack Developer", photo: "/Abdullah.jpg" },
  { name: "Abdur Razzaqe Mia", role: "MERN Stack Developer", photo: "/razzaq.jpg" },
];

function getInitials(name: string) {
  return name.split(" ").map(n => n[0]).slice(0, 2).join("").toUpperCase();
}

function getAvatarColor(name: string) {
  const colors = [
    "bg-primary/20 text-primary",
    "bg-accent/20 text-accent",
    "bg-green-500/20 text-green-500",
    "bg-purple-500/20 text-purple-500",
    "bg-pink-500/20 text-pink-500",
    "bg-yellow-500/20 text-yellow-600",
  ];
  const idx = name.charCodeAt(0) % colors.length;
  return colors[idx];
}

export default function AboutPage() {
  return (
    <>
      <Navbar />
      <main className="bg-body-bg text-foreground pt-28 pb-0">

        {/* Hero */}
        <section className="max-w-7xl mx-auto px-6 mb-20 text-center">
          <motion.p
            initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
            className="text-xs font-bold uppercase tracking-[0.25em] text-primary mb-4"
          >
            AI Learning Roadmap Generator
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}
            className="text-5xl md:text-6xl font-extrabold tracking-tight text-foreground mb-6"
          >
            About <span className="text-primary">CareerPilot</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="max-w-2xl mx-auto text-lg text-muted leading-relaxed"
          >
            CareerPilot is an AI-powered platform based on AI learning roadmap generation — helping learners build personalized roadmaps, ace mock interviews, and master in-demand skills through intelligent, data-driven guidance.
          </motion.p>
        </section>

        {/* Stats */}
        <section className="max-w-5xl mx-auto px-6 mb-24">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {STATS.map((s, i) => (
              <motion.div
                key={s.label}
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}
                className={`bg-card-bg border border-card-border rounded-2xl p-10 flex flex-col items-center text-center hover:border-primary/40 transition-all group ${s.featured ? "scale-105 border-primary/20" : ""}`}
              >
                <span className="text-4xl font-extrabold text-foreground mb-2 group-hover:scale-110 transition-transform">{s.value}</span>
                <span className="text-xs uppercase tracking-widest text-muted font-semibold">{s.label}</span>
                <div className="mt-5 w-10 h-1 bg-primary/30 rounded-full group-hover:w-16 transition-all" />
              </motion.div>
            ))}
          </div>
        </section>

        {/* Vision */}
        <section className="max-w-7xl mx-auto px-6 mb-32">
          <div className="grid grid-cols-1 md:grid-cols-12 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}
              className="md:col-span-7 rounded-2xl overflow-hidden shadow-2xl relative aspect-video"
            >
              <img
                src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=2070"
                alt="Team collaborating"
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-primary/20 to-transparent" />
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}
              className="md:col-span-5 space-y-5"
            >
              <h2 className="text-3xl font-bold text-foreground">Our Vision</h2>
              <p className="text-muted leading-relaxed">
                We believe the bridge between talent and opportunity should be paved with data, not guesswork. By empowering learners with enterprise-grade AI tools, we are leveling the playing field for the modern workforce — one personalized roadmap at a time.
              </p>
              <Link href="/dashboard" className="inline-flex items-center gap-2 font-semibold text-primary hover:gap-4 transition-all">
                Get started
                <span className="material-symbols-outlined text-xl">arrow_forward</span>
              </Link>
            </motion.div>
          </div>
        </section>

        {/* Values */}
        <section className="bg-card-bg border-y border-card-border py-24 mb-24">
          <div className="max-w-7xl mx-auto px-6">
            <div className="mb-14">
              <h2 className="text-4xl font-bold text-foreground mb-3">Driven by values</h2>
              <p className="text-muted">The core principles that guide our product development and user experience.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
              {VALUES.map((v, i) => (
                <motion.div
                  key={v.label}
                  initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }}
                  className="p-7 bg-body-bg border border-card-border rounded-2xl hover:border-primary/40 transition-all"
                >
                  <v.icon className={`w-7 h-7 ${v.color} mb-4`} />
                  <h3 className="font-bold text-base text-foreground mb-2">{v.label}</h3>
                  <p className="text-sm text-muted leading-relaxed">{v.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Team */}
        <section className="max-w-7xl mx-auto px-6 pb-24">
          <div className="text-center mb-14">
            <h2 className="text-4xl font-bold text-foreground mb-3">Our Team</h2>
            <p className="text-muted">The people building CareerPilot — based on AI Learning Roadmap Generation</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
            {TEAM.map((member, i) => (
              <motion.div
                key={member.name}
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.05 }}
                className="bg-card-bg border border-card-border rounded-2xl p-6 flex flex-col items-center text-center hover:border-primary/40 hover:shadow-lg transition-all group"
              >
                {/* Avatar or Photo */}
                {member.photo ? (
                  <div className="w-20 h-20 rounded-full overflow-hidden mb-4 border-2 border-card-border group-hover:border-primary/40 transition-colors shadow-md">
                    <img src={member.photo} alt={member.name} className="w-full h-full object-cover" />
                  </div>
                ) : (
                  <div className={`w-20 h-20 rounded-full flex items-center justify-center text-2xl font-black mb-4 border-2 border-card-border group-hover:border-primary/40 transition-colors ${getAvatarColor(member.name)}`}>
                    {getInitials(member.name)}
                  </div>
                )}
                <h3 className="font-bold text-base text-foreground mb-1 leading-snug">{member.name}</h3>
                <p className="text-[11px] uppercase tracking-widest text-muted font-semibold mb-5">{member.role}</p>
                {/* Social links */}
                <div className="flex gap-4 mt-auto">
                  <a href="#" target="_blank" rel="noopener noreferrer"
                    className="text-muted hover:text-primary transition-colors" aria-label="Twitter">
                    <Twitter className="w-4 h-4" />
                  </a>
                  <a href="#" target="_blank" rel="noopener noreferrer"
                    className="text-muted hover:text-primary transition-colors" aria-label="LinkedIn">
                    <Linkedin className="w-4 h-4" />
                  </a>
                  <a href="#" target="_blank" rel="noopener noreferrer"
                    className="text-muted hover:text-primary transition-colors" aria-label="GitHub">
                    <Github className="w-4 h-4" />
                  </a>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Join the team CTA */}
        <section className="max-w-7xl mx-auto px-6 pb-24">
          <motion.div
            initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="relative overflow-hidden bg-card-bg border border-card-border rounded-3xl p-12 text-center"
          >
            {/* Background glow */}
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-96 h-40 bg-primary/10 blur-[80px] pointer-events-none" />

            <div className="relative z-10 space-y-5 max-w-2xl mx-auto">
              <span className="inline-block text-xs font-bold uppercase tracking-[0.25em] text-primary bg-primary/10 border border-primary/20 px-4 py-1.5 rounded-full">
                We're growing
              </span>
              <h2 className="text-4xl font-extrabold text-foreground">Want to join our team?</h2>
              <p className="text-muted text-lg leading-relaxed">
                We're always looking for passionate developers, designers, and AI enthusiasts who want to shape the future of learning. If you believe in what we're building, we'd love to hear from you.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2">
                <a
                  href="mailto:careerpilot@example.com"
                  className="inline-flex items-center justify-center gap-2 px-8 py-3.5 bg-primary hover:bg-primary/90 text-white font-bold rounded-xl transition-all active:scale-95 shadow-lg shadow-primary/20"
                >
                  <span className="material-symbols-outlined text-[18px]">mail</span>
                  Get in touch
                </a>
                <a
                  href="https://github.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-center gap-2 px-8 py-3.5 bg-body-bg border border-card-border hover:border-primary/40 text-foreground font-bold rounded-xl transition-all active:scale-95"
                >
                  <Github className="w-4 h-4" />
                  View on GitHub
                </a>
              </div>
            </div>
          </motion.div>
        </section>

      </main>
      <Footer />
    </>
  );
}
